[plugins.postgres]
version = "15"

[variables]
DB_TYPE = "postgresdb"
DB_POSTGRESDB_DATABASE = "${PGDATABASE}"
DB_POSTGRESDB_HOST = "${PGHOST}"
DB_POSTGRESDB_PORT = "${PGPORT}"
DB_POSTGRESDB_USER = "${PGUSER}"
DB_POSTGRESDB_PASSWORD = "${PGPASSWORD}"

[deploy]
startCommand = "n8n start"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 8
